
/* DATA DEFINITION LANGUAGE & DATA MANIPULATION LANGUAGE*/

CREATE TABLE ADDRESS 
(
ADDRESS_ID VARCHAR(20) PRIMARY KEY , --includes primary key of the column
STREET VARCHAR(250) , 
CITY VARCHAR(100) , 
STATE VARCHAR(100) , 
COUNTRY VARCHAR(100)
);

CREATE TABLE SCHOOL 
(
SCHOOL_ID VARCHAR(20) PRIMARY KEY , --includes primary key of the column
SCHOOL_NAME VARCHAR(100) NOT NULL ,  --includes a not null constraint
EDUCATION_BOARD VARCHAR(80),
ADDRESS_ID VARCHAR(20),
CONSTRAINT FK_SCHOOL_ADDR FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) --includes a foreign key column
)

CREATE TABLE STAFF
(
STAFF_ID VARCHAR(20) PRIMARY KEY,
STAFF_TYPE VARCHAR(30),
SCHOOL_ID VARCHAR(20) , 
FIRST_NAME VARCHAR(100) NOT NULL, --includes a not null constraint , 
LAST_NAME VARCHAR(100) NOT NULL ,
AGE INT , 
DOB DATE,
GENDER VARCHAR(10) CHECK (GENDER IN ('M' , 'F', 'Male', 'Female')),
JOIN_DATE DATE ,
ADDRESS_ID VARCHAR(20),
CONSTRAINT FK_SCHOOL_ID FOREIGN KEY(SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID),
CONSTRAINT FK_ADDRESS_ID FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) -- CONSTRAINT constraint_name FOREIGN KEY(column_name) REFERENCES anothertable(column_name)
);

SELECT * FROM SCHOOL
SELECT * FROM ADDRESS
SELECT * FROM STAFF

/* DEEPER UNDERSTANDIN ON DDL AND DML 

https://www.youtube.com/watch?v=Hl4NZB1XR9c&t=2780s 
timestamp : 12:10 - 20:00



*/


